# XDCIndia Upptime Configuration

owner: XDCIndia
repo: upptime

sites:
  - name: Google
    url: https://www.google.com

  - name: Wikipedia
    url: https://en.wikipedia.org

  - name: Hacker News
    url: https://news.ycombinator.com
  - name: XDCRPC
    url: https://xdcrpc.com

status-website:
  baseUrl: /upptime

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg

  name: XDC Innovation Labs Status

  introTitle: "**XDC Innovation Labs** System Status"

  introMessage: This page shows the current status of our monitored services.

  navbar:
    - title: Status
      href: /

    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
